name: attacker-detector
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  #- cpuonly # without gpu
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - pip
  - pip:
    - xxhash
    - torch-geometric